[package]
name = "rcu_list"
version = "0.1.0"
edition = "2021"

[dependencies]
rcu_cell = "1"

[dev-dependencies]
seize = "0.4.9"
criterion = "0.3.5"
crossbeam-epoch = "0.9.8"

[[bench]]
name = "stack"
harness = false

[[bench]]
name = "queue"
harness = false